# Generated by Django 5.0.1 on 2024-03-09 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='tasks',
        ),
    ]
