# Generated by Django 5.0.1 on 2024-03-09 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_category_tasks'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='categories',
            field=models.ManyToManyField(to='category.category'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_assign_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
